Magnes Simon - Zabbix
EphecLLN/Wiki-TI pull request #11
Opened 2022-05-10 15:28 UTC by MagnesSimon

2022-05-13 08:24 UTC, vvandenschrieck requested changes
En plus de mes commentaires dans le texte, je pense qu'il serait intéressant de faire un petit tour d'horizon des solutions concurrentes à Zabbix.

2022-05-13 08:24 UTC, vvandenschrieck commented on Réseaux/Analyse Zabbix.md
> +Zabbix peut opérer de plusieurs façons pour récolter des informations. Avec un trappeur Zabbix, c’est l’hôte qui démarre une communication avec le serveur et envoie ses données. Le trappeur permet de
C'est quoi un "trappeur"?

2022-05-13 08:24 UTC, vvandenschrieck commented on Réseaux/Analyse Zabbix.md
> +
Ce serait intéressant de faire un petit schéma pour illustrer ces deux cas de figure.

2022-05-13 08:24 UTC, vvandenschrieck commented on Réseaux/Analyse Zabbix.md
> +Pour assurer la sécurité des communications entre le serveur et les machines clientes, Zabbix va appliquer un système de cryptage. De cette manière, toutes les données transmissent sont protégées lor
Chiffrement, pas cryptage

2022-05-13 08:24 UTC, vvandenschrieck commented on Réseaux/Analyse Zabbix.md
> +<Une fois arrivées sur le serveur, les données doivent être stockées. Pour cela, Zabbix utilise une base de données relationnelle sous MySQL ou PostgreSQL. Les données ainsi stockées pourront alors ê
Caractère superflu en début de phrase

2022-05-13 08:24 UTC, vvandenschrieck commented on Réseaux/Analyse Zabbix.md
> +* Découverte automatique [2]
De quoi?

2022-05-13 08:24 UTC, vvandenschrieck commented on Réseaux/Analyse Zabbix.md
> +* Intégration SNMP [7]
Explique brièvement ce qu'est SNMP

2022-05-13 08:24 UTC, vvandenschrieck commented on Réseaux/Analyse Zabbix.md
> +
Ton feedback personnel, bien qu'intéressant, n'est pas spécialement pertinent dans le cadre d'un wiki, je pense.

2022-05-13 08:24 UTC, vvandenschrieck commented on Réseaux/Analyse Zabbix.md
> +<Une fois arrivées sur le serveur, les données doivent être stockées. Pour cela, Zabbix utilise une base de données relationnelle sous MySQL ou PostgreSQL. Les données ainsi stockées pourront alors ê
Je pense qu'un schéma montrant l'architecture du système serait tout à fait pertinent ici.

2022-05-27 14:47 UTC, MagnesSimon commented
Bonjour, J'ai corriger mon analyse selon vos commentaires.

2022-05-27 20:08 UTC, vvandenschrieck commented
@MagnesSimon  C'est mieux mais attention à ta bibliographie, tu ne mets que les URLs et cela ne suffit pas!

2022-05-31 17:43 UTC, MagnesSimon commented
Voici une précision au niveau des sources

2022-06-27 10:35 UTC, merged