Les protocoles VPN
EphecLLN/Wiki-TI pull request #16
Opened 2022-05-25 12:54 UTC by HE201916

Bonjour, 

Veuillez trouver l'article sur les protocoles VPN. 

Bonne lecture

2022-05-29 20:56 UTC, LeveauArnaud commented
**Review d'un article ou d'une PR du Wiki TI**

L’article respecte bien les conventions d'édition et de soumission du Wiki TI. De plus le texte est bien structuré : introduction, liste + description des différents protocoles pour finir par une conclusion où les solutions sont comparées.


- Concernant l’introduction, 

Il serait peut-être intéressant d’expliquer un peu plus en profondeur ce qu’est un VPN, dans quelle situation utiliser un VPN, les avantages et inconvénients de l’utilisation de ce dernier.

Il serait aussi peut être intéressant d’ajouter un point sur l’histoire des VPN.

- Concernant les types de VPN, l’article en indique 2 à savoir : 

   -	Site to Site VPN
   -	Client to Site VPN
  
Un troisième type pourrait être rajouter le « SSL-VPN » ou alors une ligne tel que : « Cette liste est non exhaustive, mais reprends les solutions les plus utilisées »


-  Concernant la liste des protocoles, on retrouve 5 protocoles à savoir : 

   -	PPTP signifie Point-to-Point Protocol
   -	L2TP/ Ipsec
   -	IKEv2/IPsec : Internet Key Exchange version 2 with IPsec
   -	OpenVPN
   -	WireGuard

 Il serait peut-être intéressant de parler également des protocoles :
   -	SSTP
   -	MPLS


- Concernant la bibliographie, il serait peut-être intéressant d’y ajouter la date publication ainsi que l’auteur de chaque source. 

Il serait également intéressant d’indiquer dans le texte de quelle source provient telle ou telle information.

2022-05-31 10:29 UTC, vvandenschrieck commented
> **Review d'un article ou d'une PR du Wiki TI** @vvandenschrieck Voici mon commentaire sur l'article _des protocoles VPN_.
> 
> L’article respecte bien les conventions d'édition et de soumission du Wiki TI. De plus le texte est bien structuré : introduction, liste + description des différents protocoles pour finir par une conclusion où les solutions sont comparées.
> 
> * Concernant l’introduction,
> 
> Il serait peut-être intéressant d’expliquer un peu plus en profondeur ce qu’est un VPN, dans quelle situation utiliser un VPN, les avantages et inconvénients de l’utilisation de ce dernier.
> 
> Il serait aussi peut être intéressant d’ajouter un point sur l’histoire des VPN.
> 
> * Concernant les types de VPN, l’article en indique 2 à savoir :
>   
>   * Site to Site VPN
>   * Client to Site VPN
> 
> Un troisième type pourrait être rajouter le « SSL-VPN » ou alors une ligne tel que : « Cette liste est non exhaustive, mais reprends les solutions les plus utilisées »
> 
> * Concernant la liste des protocoles, on retrouve 5 protocoles à savoir :
>   
>   * PPTP signifie Point-to-Point Protocol
>   * L2TP/ Ipsec
>   * IKEv2/IPsec : Internet Key Exchange version 2 with IPsec
>   * OpenVPN
>   * WireGuard
> 
> Il serait peut-être intéressant de parler également des protocoles :
> 
> * SSTP
> * MPLS
> * Concernant la bibliographie, il serait peut-être intéressant d’y ajouter la date publication ainsi que l’auteur de chaque source.
> 
> Il serait également intéressant d’indiquer dans le texte de quelle source provient telle ou telle information.

Merci Arnaud pour tes remarques pertinentes.  J'y souscris, et souhaite donc que @HE201916 les intègre dans ses modifications.  

J'ajouterais également dans les demandes de modifications une description des "stacks protocolaires" de chaque technologie présentées : Distinction entre protocoles layer 2, layer 3, ... + quel protocoles est encapsulé dans quel autre protocole.

2022-05-31 10:29 UTC, vvandenschrieck requested changes
Cfr commentaires de moi-même et Arnaud dans la conversation

2022-06-06 14:48 UTC, HE201916 commented
Bonjour, 

les changements demandés ont été effectués.
En ce qui concerne MPLS, ce n'est pas un protocole VPN (je ne l'ai donc pas ajouté)

Bonne lecture.

2022-06-07 19:45 UTC, vvandenschrieck commented
il existe pourtant bien des VPNs basés sur MPLS :-).  

> Le 6 juin 2022 à 16:48, HE201916 ***@***.***> a écrit :
> 
> 
> Bonjour,
> 
> les changements demandés ont été effectués.
> En ce qui concerne MPLS, ce n'est pas un protocole VPN (je ne l'ai donc pas ajouté)
> 
> Bonne lecture.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/EphecLLN/Wiki-TI/pull/16#issuecomment-1147533180>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAPEXJD4XR43FXSE6BG4NIDVNYFU7ANCNFSM5W5BGUVQ>.
> You are receiving this because you were mentioned.
>

2022-06-08 19:44 UTC, HE201916 commented
Bonjour

Veuillez trouver mes derinières modifications .

Bonne lecture

2022-06-27 10:35 UTC, merged