added: reverse proxy + dns cache
EphecLLN/Wiki-TI pull request #46
Opened 2023-05-31 15:14 UTC by mux99

+ article sur le fonctionnement du dns cache
+ guide d'installation d'un reverse proxy

2023-06-01 12:57 UTC, vvandenschrieck commented on Réseaux/reverse_proxy_installation.md
Même remarque que pour le cache DNS en ce qui concerne l'orthographe et le style : relecture indispensable! 

Concernant le contenu : Je suis un peu moins convaincue que pour le cache DNS.  J'ai l'impression de voir un article sur différents types de proxy, et non sur le reverse proxy Web : ça manque de cohérence.  J'aimerais aussi que tu expliques plus en profondeur les fonctionnalités correspondantes à chaque configuration proposée.

2023-06-01 12:59 UTC, vvandenschrieck requested changes
Cfr commentaires sur les deux articles.

2023-06-01 17:28 UTC, mux99 commented
rajouté tls

2023-07-14 11:58 UTC, mux99 commented
près pour nouvelle évaluation

2023-07-26 13:14 UTC, vvandenschrieck commented
Beau travail d'amélioration, les articles deviennent vraiment sympa! 

Dernière petite remarque, mais néanmoins importante : dans l'article sur le TLS, l'image avec la peinture est super intéressante, mais, sauf erreur de ma part, tu n'en indiques pas la source ni en légende, ni dans la bibliographie.  C'est vraiment important d'un point de vue démarche scientifique de faire systématiquement le référencement de toute information, ressource ou média utilisé dans une contribution personnelle.

2023-07-26 14:20 UTC, mux99 commented
Référence rajoutée à la bibliographie

2023-08-27 19:56 UTC, mux99 commented
Article DKIM rajouté (brouillon) il manque le passage de correction d'orthographe et probablement quelues précisions par endroits

2023-08-28 12:52 UTC, mux99 commented
l'article DKIM est prêt pour évaluation

2023-08-28 18:13 UTC, vvandenschrieck approved these changes

2024-04-09 13:10 UTC, closed without merging