Https
EphecLLN/Wiki-TI pull request #5
Opened 2022-05-01 21:44 UTC by Rachiid007

Bonjour, ceci est mon article à propos du protocole HTTPS.

Bien à vous,

Abderrachid BELLAALI

2022-05-02 10:41 UTC, vvandenschrieck requested changes
En plus des commentaires dans le texte, encore un commentaire général : Ta bibliographie n'est pas exploitée dans le texte.  Indique pour chaque élément d'information le numéro de la source dont il provient.

2022-05-02 10:41 UTC, vvandenschrieck commented on Réseaux/https.md
> +    Aucun changement nécessaire dans le protocole applicatif n'englobé.
"n'englobé"?

2022-05-02 10:41 UTC, vvandenschrieck commented on Réseaux/https.md
> +![image](https://user-images.githubusercontent.com/91373823/166163525-721fb773-5093-4672-8812-efc90ac67c41.png)
Ajoute la source de l'image

2022-05-02 10:41 UTC, vvandenschrieck commented on Réseaux/https.md
> +Un certificat c'est comme la carte d'identité d'un serveur, il permet d'assurer que vos etes bien la personne qui prétender l'être. Pour cela, il faudrait passer par une autorité de certificat (autor
"que vous êtes bien la personne que vous prétendez être". 
"autorité de certificat" => "autorité de certification"
"autorité reconnue, validée, sûre, qui peut délivrer des certificats"
Utilise l'indicatif présent plutôt que le conditionnel.

2022-05-02 10:41 UTC, vvandenschrieck commented on Réseaux/https.md
> +
Cette section est bancale et pas suffisamment claire.  Essaie de retravailler le texte.

2022-05-08 23:10 UTC, Rachiid007 commented
Bonjour Madame Van Den Schrieck, je viens d'apporter les changements nécessaires à mon article.

Pouvez-vous l'évaluer de nouveau?

Merci.

2022-05-10 09:24 UTC, vvandenschrieck requested changes

2022-05-10 09:24 UTC, vvandenschrieck commented on Réseaux/https.md
> +-   dîtes TLS et pas SSL (déprécier) !
- dites TLS et pas SSL (déprécié!)

2022-05-10 09:24 UTC, vvandenschrieck commented on Réseaux/https.md
> +-   Utiliser les outils d'automatisation TLS (Let’s encrypt/ACME)
- Utilisez les outils

2022-05-10 09:24 UTC, vvandenschrieck commented on Réseaux/https.md
> +</p>
A vérifier : Est-ce que tu as le droit de réutiliser l'image?

2022-05-10 09:26 UTC, vvandenschrieck commented
Globalement l'article me convient, à quelques détails près.  Je valide l'évaluation TLCA, mais j'aimerais que tu fasses les quelques changements demandés avant que je ne fasse le merge.

2022-05-10 09:50 UTC, Rachiid007 commented on Réseaux/https.md
> +</p>
Je n'en ai pas la moindre idée 🤔

2022-05-10 09:51 UTC, Rachiid007 commented
Et voilà, madame, c'est fait 😊

2022-05-10 10:03 UTC, merged