Reverse proxy
EphecLLN/Wiki-TI pull request #7
Opened 2022-05-05 20:54 UTC by KeviinKeurvels

Bonjour madame,
J'ai finalisé mon article. Pouvez-vous le corriger dans le but de le faire valider sur TLCA ?
Merci et bonne soirée,
Kevin Keurvels HE201913

2022-05-06 09:38 UTC, vvandenschrieck requested changes
- Présentation du proxy : ta définition est très générale.  En pratique, un proxy est un appareil intermédiaire qui agit au niveau de la couche applicative, et qui intervient comme acteur au niveau des échanges protocolaires.  Par exemple, un proxy HTTP se mettra entre la source et la destination d'un échange HTTP.  Il va donc logiquement "parler" le HTTP. Il existe donc potentiellement plein de sortes de proxy, chacun ayant ses spécificités en fonction du ou des protocoles supportés.  Il existe même des proxies au  niveau de la couche transport (par ex. HAProxy)
- Du coup, c'est un peu restrictif de ne mentionner que les proxy DNS et Web, indique bien que ce ne sont que deux exemples parmi beaucoup.    
- Dans les usages du reverse proxy, je pense que tu pourrais aussi mentionner le rôle de "terminateur SSL"
- Bibliographie : Les numéros n'apparaissent pas, donc on ne sait pas faire le lien entre les sources citées et la biblio.

2022-05-06 09:38 UTC, vvandenschrieck commented on reverse_proxy.md
> +Un utilisateur passera par le reverse proxy pour accéder aux services internes. De cette façon, il permet de rajouter une sécurité supplémentaire et protége les serveurs des attaques potentielles ven
"pour accéder aux services internes" : Je n'utiliserais pas le qualificatif "internes" ici. Les services en question sont publics puisque accessibles depuis l'internet, mais simplement ils ne sont pas "en première ligne".

2022-05-06 09:38 UTC, vvandenschrieck commented on reverse_proxy.md
> +De temps en temps, le reverse proxy ira demander au serveur si les données qu'il a stocké son toujours à jour ou si le contenu des pages ont changés. Si ce n'est plus le cas, il demande les nouvelles
"sonT" à jour
"le contenu des pages A CHANGE"

2022-05-06 09:38 UTC, vvandenschrieck commented on reverse_proxy.md
> +Il n'est pas rare dans une entreprise d'avoir plusieurs serveurs (Web par exemple) de telle façon que si un serveur devient inaccessible pour une raison ou une autre (panne, surcharge,...), le servic
Attention, ce que tu décris, c'est plutôt le principe de "redondance".  La répartition de charge, c'est d'avoir plusieurs serveurs pour répartir les requêtes et optimiser les performances.  
On pourrait par ex. avoir un second serveur pour la redondance, mais qui n'intervient que quand le premier tombe.  Comme il ne fait rien tant qu'il n'y a pas de panne, il n'y a pas de répartition de charge.

2022-05-06 09:38 UTC, vvandenschrieck commented on reverse_proxy.md
> +On peut installer, sur un reverse proxy, des antivirus ou des filtres de paquet pour analyser plus en profondeur les paquets reçus, ce qui permet de sécuriser les paquets qui atteignent les serveurs.
filtres de paquetS

2022-05-06 09:38 UTC, vvandenschrieck commented on reverse_proxy.md
> +Le reverse proxy se charge donc de filtrer les paquets sortant du réseau (typiquement des réponses des différents serveurs) et d'arrêter certains paquets contenant, justement, ces fameuses erreurs. I
"Information considéréE comme désirée"
Je ne comprend pas bien le fait d'arrêter l'envoi des tokens. C'est une bonne ou une mauvaise chose?

2022-05-07 13:11 UTC, KeviinKeurvels commented
Bonjour madame,
j'ai apporté les changements demandés.

2022-05-10 10:44 UTC, merged