Comparatif sip h323
EphecLLN/Wiki-TI pull request #9
Opened 2022-05-08 13:30 UTC by CastermaneRobin

Article Wiki comparant le protocole **SIP** avec le protocole **H.323**.

2022-05-13 07:48 UTC, vvandenschrieck requested changes
- Bibliographie : Tu dois indiquer dans ton texte quelle information vient de quelle source, en numérotant ces dernières.  
- Le protocole H323 a été standardisé par l'IEEE et non l'IETF.  Je pense que c'est une différence significative, car du coup, SIP est plus "conforme" aux autres protocoles applicatifs Internet que H323.  
- Je trouve qu'il manque deux schémas illustrant une communication VoIP (session + multimedia) avec chacun des systèmes comparés.

2022-05-13 07:52 UTC, vvandenschrieck commented on Réseaux/Comparatif entre SIP et h323.md
> +   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;La « Session Initiation Protocol » (SIP) est un protocole TCP/IP de couche application normalisée et standardisé par l’IETF*. Il s’agit d’un protocole de commun
Relis la grammaire de cette phrase.

2022-05-13 07:52 UTC, vvandenschrieck commented on Réseaux/Comparatif entre SIP et h323.md
> +   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Le protocole SIP permet d’établir une « sessions » entre deux ou plus de participants, de modifier cette session et finalement de mettre fin à cette session.
pluriel superflu

2022-05-13 07:52 UTC, vvandenschrieck commented on Réseaux/Comparatif entre SIP et h323.md
> +   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Existant depuis 1996, Il est considéré comme assez ancien. C’est un protocole binaire et se fait remplacer par le SIP.
Tu dis ici que h323 est considéré comme ancien, mais plus bas, tu indiques que SIP et H323 sont apparus à la même époque.  C'est un peu contradictoire.

2022-05-13 07:52 UTC, vvandenschrieck commented on Réseaux/Comparatif entre SIP et h323.md
> +   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SIP et H323 sont des protocoles de communications utilisés pour les appels multimédia et la téléconférence sur des réseaux basés sur le protocole Internet.
protocoles de communication

2022-05-13 07:52 UTC, vvandenschrieck commented on Réseaux/Comparatif entre SIP et h323.md
> +| Evolution du protocole | Protocole ouvert à des nouvelles fonctions | Ajout d'extensions propriétaires sans concertation entre vendeurs |
A quoi est-ce dû?

2022-05-13 07:52 UTC, vvandenschrieck commented on Réseaux/Comparatif entre SIP et h323.md
> +| Fonction de conférence | Distribuée | Centralisée par l'unité MC |
Que veux-tu dire par "conférence"? Qu'est ce que l'unité MC?

2022-05-13 07:52 UTC, vvandenschrieck commented on Réseaux/Comparatif entre SIP et h323.md
> +| Fonction de téléservices | Oui, par défaut | H.323 V2 + H.450 |
C'est quoi un téléservice?

2022-05-13 07:52 UTC, vvandenschrieck commented on Réseaux/Comparatif entre SIP et h323.md
> +   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;H323 est plus fiable que SIP en raison de sa capacité à gérer les défaillances des connexions et des périphériques réseau, tandis que SIP manque de mécanismes d
Pourrais-tu expliquer en deux mots comment H323 effectue cette gestion des défaillances?

2022-05-13 07:52 UTC, vvandenschrieck commented on Réseaux/Comparatif entre SIP et h323.md
> +   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;H323 défini un certain nombre de fonctionnalités pour gérer la défaillance des entités de réseau intermédiaire. SIP ne définit pas de procédures en cas de panne
Idem que plus haut

2022-05-19 09:39 UTC, CastermaneRobin commented
J'ai effectué les changements qui m'ont été demandés afin d'améliorer mon article et j'ai réalisé moi-même les deux schémas.

2022-05-20 09:59 UTC, merged